autoupdate:
  devel: false
  enabled: false
  image:
    pullPolicy: IfNotPresent
    repository: alpine/k8s
    tag: 1.32.3
  schedule: '@daily'
aws_fargate:
  enabled: false
  logs:
    enabled: false
    filters: ''
    region: null
  metrics:
    autodiscovery:
      affinity: {}
      batch:
        send_batch_max_size: 512
        send_batch_size: 512
        timeout: 1s
      memory_limiter:
        check_interval: 1s
        limit_mib: 2560
        spike_limit_mib: 512
      nodeSelector: {}
      resources:
        limits:
          memory: 3Gi
        requests:
          memory: 3Gi
      retry_on_failure:
        enabled: true
        initial_interval: 10s
        max_elapsed_time: 300s
        max_interval: 30s
      sending_queue:
        enabled: true
        num_consumers: 20
        offload_to_disk: false
        queue_size: 1000
      telemetry:
        logs:
          enabled: true
          level: info
        metrics:
          address: 0.0.0.0:8888
          enabled: true
      timeout: 15s
      tolerations: []
beyla:
  affinity: {}
  config: {}
  enabled: false
  extraCapabilities: []
  image:
    pullPolicy: IfNotPresent
    repository: grafana/beyla
    tag: 2.1.0
  nodeSelector: {}
  resources:
    limits:
      cpu: 500m
      memory: 768Mi
    requests:
      cpu: 100m
      memory: 128Mi
  tolerations: []
certmanager:
  enabled: false
  installCRDs: true
cluster:
  filter:
    exclude_namespaces: []
    exclude_namespaces_regex: []
    include_namespaces: []
    include_namespaces_regex: []
  name: <CLUSTER_NAME>
  uid: ''
ebpfNetworkMonitoring:
  enabled: true
  k8sCollector:
    enabled: true
    relay:
      image:
        pullPolicy: IfNotPresent
        repository: solarwinds/opentelemetry-ebpf-k8s-relay
        tag: v0.10.3
    telemetry:
      logs:
        level: warning
    watcher:
      image:
        pullPolicy: IfNotPresent
        repository: solarwinds/opentelemetry-ebpf-k8s-watcher
        tag: v0.10.3
  kernelCollector:
    affinity: {}
    enabled: true
    image:
      pullPolicy: IfNotPresent
      repository: solarwinds/opentelemetry-ebpf-kernel-collector
      tag: v0.10.3
    nodeSelector: {}
    resources:
      requests:
        memory: 50Mi
    telemetry:
      logs:
        level: warning
    tolerations: []
  reducer:
    disableMetrics: []
    enableIdIdGeneration: false
    enableMetrics: []
    image:
      pullPolicy: IfNotPresent
      repository: solarwinds/opentelemetry-ebpf-reducer
      tag: v0.10.3
    numAggregationShards: 3
    numIngestShards: 3
    numMatchingShards: 3
    telemetry:
      logs:
        level: warning
      metrics:
        enabled: false
    telemetryPort: 7000
fullnameOverride: ''
imagePullSecrets: []
kube-state-metrics:
  enabled: true
  nodeSelector:
    kubernetes.io/os: linux
  prometheusScrape: false
nameOverride: ''
openshift:
  enabled: false
operator:
  admissionWebhooks:
    certManager:
      certificateAnnotations:
        helm.sh/hook: post-install,post-upgrade
        helm.sh/hook-weight: '1'
      enabled: true
      issuerAnnotations:
        helm.sh/hook: post-install,post-upgrade
        helm.sh/hook-weight: '1'
  enabled: false
  manager:
    autoInstrumentationImage:
      dotnet:
        repository: ''
        tag: ''
      go:
        repository: ''
        tag: ''
      java:
        repository: solarwinds/autoinstrumentation-java
        tag: 2.13.0
      nodejs:
        repository: ''
        tag: ''
      python:
        repository: solarwinds/autoinstrumentation-python
        tag: 3.6.0
    collectorImage:
      repository: solarwinds/swi-opentelemetry-collector
    image:
      repository: ghcr.io/open-telemetry/opentelemetry-operator/opentelemetry-operator
      tag: 0.119.0
    targetAllocatorImage:
      repository: ''
      tag: ''
otel:
  api_token: ''
  endpoint: <OTEL_ENVOY_ADDRESS>
  events:
    affinity: {}
    batch:
      send_batch_max_size: 64
      send_batch_size: 64
      timeout: 1s
    enabled: true
    filter: {}
    k8s_instrumentation:
      annotations:
        enabled: false
        excludePattern: ''
      labels:
        enabled: false
        excludePattern: ''
    memory_limiter:
      check_interval: 1s
      limit_mib: 800
      spike_limit_mib: 300
    nodeSelector: {}
    resources:
      limits:
        memory: 1000Mi
      requests:
        memory: 1000Mi
    retry_on_failure:
      enabled: true
      initial_interval: 10s
      max_elapsed_time: 300s
      max_interval: 30s
    sending_queue:
      enabled: true
      num_consumers: 10
      offload_to_disk: false
      queue_size: 1000
    telemetry:
      logs:
        enabled: true
        level: info
      metrics:
        address: 0.0.0.0:8888
        enabled: true
        podMonitor:
          additionalLabels: {}
          enabled: false
          interval: 60s
          namespace: null
          scrapeTimeout: 25s
    terminationGracePeriodSeconds: 600
    timeout: 15s
    tolerations: []
  https_proxy_url: ''
  image:
    pullPolicy: IfNotPresent
    repository: solarwinds/solarwinds-otel-collector
    tag: 0.119.12
  init_images:
    busy_box:
      pullPolicy: IfNotPresent
      repository: busybox
      tag: 1.36.1
  logs:
    affinity: {}
    batch:
      send_batch_max_size: 512
      send_batch_size: 512
      timeout: 1s
    container: true
    enabled: true
    filestorage:
      directory: /var/lib/swo/checkpoints
      fsync: true
      timeout: 5s
    filter: {}
    journal: true
    k8s_instrumentation:
      annotations:
        enabled: false
        excludePattern: ''
      labels:
        enabled: false
        excludePattern: ''
    memory_limiter:
      check_interval: 1s
      limit_mib: 800
      spike_limit_mib: 300
    nodeSelector: {}
    receiver:
      encoding: utf-8
      fingerprint_size: 1kb
      max_concurrent_files: 10
      max_log_size: 1MiB
      poll_interval: 200ms
      start_at: end
    resources:
      limits:
        memory: 1Gi
      requests:
        memory: 50Mi
    telemetry:
      logs:
        enabled: true
        level: info
      metrics:
        address: 0.0.0.0:8888
        enabled: true
        podMonitor:
          additionalLabels: {}
          enabled: false
          interval: 60s
          namespace: null
          scrapeTimeout: 25s
    tolerations: []
  manifests:
    enabled: true
    filter: {}
    persistent_storage:
      enabled: false
      storageClassName: ''
    pull_every: 60m
  metrics:
    affinity: {}
    autodiscovery:
      discovery_collector:
        affinity: {}
        autoscaler: {}
        batch:
          send_batch_max_size: 512
          send_batch_size: 512
          timeout: 1s
        enabled: false
        memory_limiter:
          check_interval: 1s
          limit_mib: 800
          spike_limit_mib: 300
        nodeSelector: {}
        resources:
          limits:
            memory: 1Gi
          requests:
            memory: 50Mi
        retry_on_failure:
          enabled: true
          initial_interval: 10s
          max_elapsed_time: 300s
          max_interval: 30s
        sending_queue:
          enabled: true
          num_consumers: 20
          queue_size: 1000
        targetAllocator:
          affinity: {}
          nodeSelector: {}
          podMonitorSelector: {}
          probeSelector: {}
          scrapeConfigSelector: {}
          serviceMonitorSelector: {}
          tolerations: []
        telemetry:
          logs:
            enabled: true
            level: info
          metrics:
            address: 0.0.0.0:8888
            enabled: true
        timeout: 15s
        tolerations: []
      prefix: k8s.
      prometheusEndpoints:
        additionalRules: ''
        customTransformations:
          counterToRate: []
        enabled: true
        filter: {}
        podMonitors:
          rules: []
    batch:
      send_batch_max_size: 512
      send_batch_size: 512
      timeout: 1s
    control_plane:
      controller_manager:
        enabled: true
        label_selector:
          key: component
          value: kube-controller-manager
        metrics_path: /metrics
        port: 10257
        scheme: https
      coredns:
        enabled: true
      etcd:
        enabled: true
        label_selector:
          key: component
          value: etcd
        metrics_path: /metrics
        port: 2379
        scheme: http
        scrape_kind: pod
        static_endpoints: []
    enabled: true
    extra_scrape_metrics: []
    filter: {}
    force_extra_scrape_metrics: false
    k8s_instrumentation:
      annotations:
        enabled: false
        excludePattern: ''
      labels:
        enabled: false
        excludePattern: ''
    kube-state-metrics:
      scheme: http
      scrape_interval: 60s
      url: ''
    livenessProbe:
      initialDelaySeconds: 10
    memory_limiter:
      check_interval: 1s
      limit_mib: 2560
      spike_limit_mib: 512
    nodeSelector: {}
    otlp_endpoint:
      port: 4317
    prometheus:
      scheme: http
      scrape_interval: 60s
      url: ''
    prometheus_check: false
    readinessProbe:
      initialDelaySeconds: 10
    resources:
      limits:
        memory: 3Gi
      requests:
        memory: 3Gi
    retry_on_failure:
      enabled: true
      initial_interval: 10s
      max_elapsed_time: 300s
      max_interval: 30s
    sending_queue:
      enabled: true
      num_consumers: 20
      offload_to_disk: false
      queue_size: 1000
    telemetry:
      logs:
        enabled: true
        level: info
      metrics:
        address: 0.0.0.0:8888
        enabled: true
        podMonitor:
          additionalLabels: {}
          enabled: false
          interval: 60s
          namespace: null
          scrapeTimeout: 25s
    terminationGracePeriodSeconds: 600
    timeout: 15s
    tolerations: []
  node_collector:
    retry_on_failure:
      enabled: true
      initial_interval: 10s
      max_elapsed_time: 300s
      max_interval: 30s
    sending_queue:
      enabled: true
      num_consumers: 20
      persistent_storage:
        directory: /var/lib/swo/sending_queue
        enabled: false
      queue_size: 1000
    terminationGracePeriodSeconds: 600
    timeout: 15s
  swi_endpoint_check:
    enabled: true
  tls_insecure: false
  windows:
    enabled: true
    image:
      pullPolicy: IfNotPresent
      repository: solarwinds/solarwinds-otel-collector
      tag: 0.119.12
prometheusCRDs:
  install: false
swoagent:
  affinity: {}
  enabled: false
  image:
    pullPolicy: IfNotPresent
    repository: solarwinds/swo-agent
    tag: v2.10.165
  nodeSelector: {}
  resources:
    limits:
      memory: 800Mi
    requests:
      cpu: 100m
      memory: 800Mi
  serviceAccountName: null
  storageClassName: null
waitJobs:
  certmanager:
    enabled: true
    image:
      pullPolicy: IfNotPresent
      repository: alpine/k8s
      tag: 1.27.16
  operator:
    enabled: true
    image:
      pullPolicy: IfNotPresent
      repository: alpine/k8s
      tag: 1.32.3
