name: Update Docker Images

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * 1'

jobs:
  update-images:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with: 
          python-version: '3.11'

      - name: Install deps
        run: pip install ruamel.yaml requests packaging PyGithub

      - name: Check for existing PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          EXISTING_PR=$(gh pr list --state open --head update-images --json number -q '.[0].number')
          echo "EXISTING_PR=$EXISTING_PR" >> $GITHUB_ENV

      - name: Setup update branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ -z "${{ env.EXISTING_PR }}" ]; then
            # Create new branch if PR doesn't exist
            BASE_SHA=$(gh api repos/${{ github.repository }}/git/ref/heads/master -q .object.sha)
            gh api repos/${{ github.repository }}/git/refs \
              -f ref="refs/heads/update-images" \
              -f sha="$BASE_SHA" || echo "Branch already exists"
            git fetch origin update-images
            git checkout update-images
          else
            # Checkout the existing PR branch if it exists
            git fetch origin update-images
            git checkout -b temp-branch
            # Run updates on temp branch
            git checkout update-images
          fi

      - name: Run updater
        run: |
          python utils/update_images.py --github-token ${{ secrets.GITHUB_TOKEN }} --update-chart
          if [ $? -ne 0 ]; then
            echo "No changes detected. Exiting."
            exit 0
          fi

      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add deploy/helm/values.yaml deploy/helm/Chart.yaml
          git commit -m "chore: update Docker image versions" || echo "No changes to commit"
          git push -f origin update-images

      - name: Update existing PR
        if: env.EXISTING_PR != ''
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          CHANGES=$(cat changes.log)
          EXISTING_BODY=$(gh pr view ${{ env.EXISTING_PR }} --json body -q .body)
          NEW_BODY="$EXISTING_BODY
          $CHANGES"
          gh pr edit ${{ env.EXISTING_PR }} --body "$NEW_BODY"

      - name: Create Pull Request
        if: env.EXISTING_PR == ''
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          CHANGES=$(cat changes.log)
          gh pr create \
            --title "Update Docker image versions" \
            --body "$CHANGES" \
            --head update-images \
            --base master

      - name: Clean up changes.log
        if: success()
        run: rm changes.log || true
