name: Update Docker Images

on:
  schedule:
    # every monday at 9:00 am utc
    - cron: '0 9 * * 1'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-images:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests packaging ruamel.yaml PyGithub
    
    - name: Configure Git for GitHub Actions
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git config --global commit.gpgsign false
        git config --global init.defaultBranch main
        git config --global push.autoSetupRemote true
    
    - name: Run image update script
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPOSITORY: ${{ github.repository }}
      run: |
        python utils/update_images.py \
          --github-token "$GITHUB_TOKEN" \
          --repository "$REPOSITORY" \
          --update-chart \
          --pr-mode
    
    - name: Check workflow status
      if: failure()
      run: |
        echo "Image update workflow failed. Check the logs above for details."
        exit 1
