name: Update Docker Images

on:
  schedule:
    # Run every Monday at 9:00 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Run in dry-run mode (only show what would be updated)'
        required: false
        default: false
        type: boolean
      filter:
        description: 'Filter images by repository name (optional)'
        required: false
        type: string

permissions:
  contents: write
  pull-requests: write

jobs:
  update-images:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: ./utils
    
    - name: Configure Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
    
    - name: Run image update script
      run: |
        python update_images.py \
          --github-token "${{ secrets.GITHUB_TOKEN }}" \
          --repository "${{ github.repository }}" \
          --update-chart \
          --values-file "deploy/helm/values.yaml" \
          --chart-file "deploy/helm/Chart.yaml" \
          --branch-name "update-images" \
          ${{ github.event.inputs.dry_run == 'true' && '--dry-run' || '' }} \
          ${{ github.event.inputs.filter && format('--filter "{0}"', github.event.inputs.filter) || '' }}
      working-directory: ./utils
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Upload changes log
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: changes-log
        path: utils/changes.log
        retention-days: 30
        if-no-files-found: ignore
